version: "3.7"
services:
  web:
    build: .
    image: net_working/ruby:latest
    container_name: net_working_web
    command: "rails s -b 0.0.0.0"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - database
    ports:
      - "3000:3000"
      - "587:587"
  database:
    image: postgres:latest
    restart: always
    container_name: net_working_db
    volumes:
      - ../.postgres/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
